version: '3.7'
services:
  backend:
    container_name: backend
    build:
      context: .
      target: development
    volumes:
      - .:/usr/server
      - /usr/server/node_modules
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - db
    ports: 
      - 8000:8000

  # db:
  #   container_name: db
  #   image: mongo
  #   restart: always
  #   ports: 
  #     - 27017:27017